/**
 * Engels, met de Nederlandse tekst als sleutel. Wat hier niet staat, blijft
 * Nederlands — dus een ontbrekende regel zie je meteen in de app.
 * Plaatshouders {0}, {1} komen overeen met de rij die t() meekrijgt.
 */
export const EN: Record<string, string> = {
  // Tabs en kop
  'Vandaag': 'Today',
  'Lijst': 'List',
  'Recepten': 'Recipes',
  'Bonus': 'Bonus',
  'Voorraad': 'Pantry',
  'Onderdelen': 'Sections',
  'CoupleCart': 'CoupleCart',
  'Lijst delen': 'Share list',
  'Thema en meer': 'Theme and more',
  'Thema': 'Theme',
  'Taal': 'Language',
  'Zoals je telefoon': 'Same as your phone',
  'Licht': 'Light',
  'Donker': 'Dark',
  'Je tegoed': 'Your allowance',
  'Beheer': 'Admin',
  'Voorwaarden en privacy': 'Terms and privacy',
  'Hulp nodig?': 'Need help?',
  'Steun CoupleCart': 'Support CoupleCart',
  'Uitloggen': 'Sign out',
  'Welkom bij Plus': 'Welcome to Plus',
  'Alles staat voor jullie allebei open.': 'Everything is open to both of you.',
  'Betaling afgebroken': 'Payment cancelled',
  'Er is niets afgeschreven.': 'Nothing was charged.',
  'Geen bereik. Je wijzigingen gaan mee zodra je weer online bent.': 'No connection. Your changes will sync once you are back online.',
  'Deze pagina bestaat niet': 'This page does not exist',
  'Naar je lijst': 'Go to your list',

  // Vandaag
  'Welkom': 'Welcome',
  'Alles klaar': 'All done',
  'Wat eten we?': 'What are we eating?',
  'Goedemorgen': 'Good morning',
  'Goedemiddag': 'Good afternoon',
  'Goedenavond': 'Good evening',
  'Vanavond eten we': 'Tonight we are having',
  'Vanavond': 'Tonight',
  'Vanavond: {0}': 'Tonight: {0}',
  'Morgen: {0}': 'Tomorrow: {0}',
  'Voor {0} · {1} ingrediënten': 'Serves {0} · {1} ingredients',
  ', alles in huis': ', all at home',
  'alles in huis': 'all at home',
  'Voor vanavond gekozen': 'Chosen for tonight',
  'persoon': 'person',
  'personen': 'people',
  'ding': 'thing',
  'dingen': 'things',
  '{0} halen': '{0} to get',
  '· in de bonus, ± {0} minder': '· on offer, about {0} less',
  'Bekijk recept': 'View recipe',
  'Kies een recept': 'Choose a recipe',
  'Ruilen': 'Swap',
  'Uit jullie recepten · kunnen vanavond': 'From your recipes · possible tonight',
  'Kies': 'Choose',
  'Alle {0} recepten': 'All {0} recipes',
  'Nog niets gepland — en nog geen recepten om uit te kiezen': 'Nothing planned yet — and no recipes to choose from',
  'Zet er één in. Vanaf dan staat hier elke dag wat jullie eten, en de boodschappen ervoor gaan vanzelf op de lijst.': 'Add one. From then on this shows what you are eating each day, and the groceries for it go on the list by themselves.',
  'Eerste recept toevoegen': 'Add your first recipe',
  'Op je lijst': 'On your list',
  '· {0} te halen': '· {0} to get',
  'Ordenen': 'Organise',
  '± {0} bij AH': 'about {0} at AH',
  ' · {0} in de bonus': ' · {0} on offer',
  'Nog geen AH-prijzen': 'No AH prices yet',
  'Begin met': 'Start with',
  'Zet erbij': 'Add',
  'Alles gehaald. Wat je afvinkte staat nu in je voorraad.': 'Everything bought. What you checked off is now in your pantry.',
  'Nog niets te halen. Typ wat je nodig hebt, of zet een recept op je lijst.': 'Nothing to get yet. Type what you need, or put a recipe on your list.',
  'Iets anders toevoegen': 'Add something else',
  'Vink {0} af': 'Check off {0}',
  'Deze week in de bonus': 'On offer this week',
  'Uit jullie recepten · plan ze alvast in': 'From your recipes · plan them ahead',
  '{0} in de bonus · ± {1} minder': '{0} on offer · about {1} less',
  '{0} in de bonus': '{0} on offer',
  '· in de bonus': '· on offer',
  'Plan': 'Plan',
  'Naar Bonuschef': 'Go to Bonuschef',
  'Morgen nog niets gepland': 'Nothing planned for tomorrow yet',
  'Wat eten we vanavond?': 'What are we eating tonight?',
  'Wat eten we {0}?': 'What are we eating {0}?',
  'Kies een recept uit je eigen lijst.': 'Choose a recipe from your own list.',
  'Nog geen recepten': 'No recipes yet',
  'Plak een link van een recept, dan kun je hem hier kiezen.': 'Paste a link to a recipe and you can choose it here.',
  'Naar recepten': 'Go to recipes',
  'voor {0}': 'for {0}',
  'Nu': 'Now',
  '“{0}” afgevinkt': '“{0}” checked off',
  '“{0}” op je lijst': '“{0}” on your list',
  'Ongedaan maken': 'Undo',

  // Lijst
  'Samen boodschappen': 'Groceries together',
  'Je lijst wordt opgehaald': 'Loading your list',
  'Nog niets op je lijst': 'Nothing on your list yet',
  '{0} te halen · {1} in de kar': '{0} to get · {1} in the cart',
  'Lijst leegmaken': 'Clear list',
  'Wat moet je halen?': 'What do you need?',
  'Toevoegen': 'Add',
  'Op afdeling': 'By aisle',
  'Op volgorde': 'In order',
  'Winkelmodus': 'Shopping mode',
  'Winkelmodus sluiten': 'Close shopping mode',
  'Meer met deze lijst': 'More for this list',
  'Dubbele samenvoegen': 'Merge duplicates',
  'Hele lijst leegmaken?': 'Clear the whole list?',
  'De boodschap verdwijnt, ook voor wie meekijkt.': 'The item disappears, also for anyone viewing along.',
  'Alle {0} boodschappen verdwijnen, ook voor wie meekijkt.': 'All {0} items disappear, also for anyone viewing along.',
  'Annuleren': 'Cancel',
  'Leegmaken': 'Clear',
  'Schone lei': 'Clean slate',
  'Begin met typen, of haal een recept op. Jullie zien allebei direct hetzelfde.': 'Start typing, or fetch a recipe. You both see the same thing right away.',
  'Product toevoegen': 'Add a product',
  'Uit een recept': 'From a recipe',
  'In de kar': 'In the cart',
  '· {0} op': '· {0} out',
  'Alles uit de kar weghalen': 'Remove everything from the cart',
  'Zet {0} terug op je lijst': 'Put {0} back on your list',
  'niet gevonden bij AH': 'not found at AH',
  'Bekijk wat het kost bij AH': 'See what it costs at AH',
  'In mandje': 'To basket',
  '· {0} in de bonus': '· {0} on offer',
  'Prijzen zoeken…': 'Finding prices…',
  'AH-prijzen verversen': 'Refresh AH prices',
  'Totaal bij AH': 'Total at AH',
  '· je bespaart {0}': '· you save {0}',
  '{0} van {1} gevonden': '{0} of {1} found',
  '· Je bestelt bij AH, in de app of op ah.nl.': '· You order at AH, in the app or on ah.nl.',
  'Alle {0} boodschappen gevonden bij AH': 'All {0} items found at AH',
  '{0} van {1} boodschappen gevonden bij AH': '{0} of {1} items found at AH',
  'AH-prijzen ophalen lukte niet. Controleer je verbinding en probeer het opnieuw.': 'Could not fetch AH prices. Check your connection and try again.',
  'Toevoegen lukte niet. Probeer het opnieuw.': 'Adding failed. Please try again.',
  'Verwijderen lukte niet. Probeer het opnieuw.': 'Removing failed. Please try again.',
  'Samenvoegen met dubbel item': 'Merge with duplicate item',
  'Opties voor {0}': 'Options for {0}',
  'Verwijder {0}': 'Remove {0}',
  'Verwijderen': 'Remove',
  'Weggooien': 'Delete',
  'Afvinken': 'Check off',
  'Veeg naar rechts om af te vinken': 'Swipe right to check off',
  'Zoek bij Albert Heijn': 'Search at Albert Heijn',
  'Zoek bij Jumbo': 'Search at Jumbo',
  'Naam': 'Name',
  'Wijzig je de naam, dan vervalt het gekozen AH-product.': 'If you change the name, the chosen AH product is dropped.',
  'uit {0}': 'from {0}',
  'Product bij AH kiezen': 'Choose an AH product',
  'Kies een ander product': 'Choose another product',
  'Voor {0}': 'For {0}',
  'Producten bij AH': 'Products at AH',
  ' · nu gekozen': ' · currently chosen',
  'Andere producten ophalen lukte niet.': 'Could not fetch other products.',
  'AH heeft geen andere producten voor deze boodschap.': 'AH has no other products for this item.',
  'Aantal:': 'Quantity:',
  'Eén minder': 'One less',
  'Eén meer': 'One more',
  'Minder': 'Less',
  'Meer': 'More',
  'Bekijk op ah.nl': 'View on ah.nl',
  'Gebruik dit product': 'Use this product',
  'Opnieuw proberen': 'Try again',
  'Zelf een product toevoegen': 'Add a product yourself',
  'Als PDF': 'As PDF',
  'Via WhatsApp': 'Via WhatsApp',
  'PDF gedownload': 'PDF downloaded',
  'Je lijst is leeg, er valt niets te downloaden': 'Your list is empty, there is nothing to download',
  'Je lijst is leeg, er valt niets te sturen': 'Your list is empty, there is nothing to send',
  'Boodschappen': 'Groceries',
  'Gedeeld lijstje 🛒': 'Shared list 🛒',
  'Of stuur de lijst zelf': 'Or send the list yourself',
  'Kopieer link': 'Copy link',
  'Link gekopieerd!': 'Link copied!',
  'Lijstje niet gevonden': 'List not found',
  'Laden...': 'Loading...',

  // Winkelmodus
  'Alles gehaald': 'All done',
  'Je kar is compleet.': 'Your cart is complete.',
  'Terug naar je lijst': 'Back to your list',
  'Afdeling {0} van {1} · nog {2} hier': 'Aisle {0} of {1} · {2} left here',
  'Deze afdeling is klaar': 'This aisle is done',
  'Nog {0} op andere afdelingen.': '{0} left in other aisles.',
  'Klaar met deze afdeling': 'Done with this aisle',
  'Volgende afdeling': 'Next aisle',
  'Niets meer te halen': 'Nothing left to get',
  'Afronden': 'Finish',
  'Klaar': 'Done',

  // Afdelingen
  'Groente & fruit': 'Fruit & vegetables',
  'Brood & bakkerij': 'Bread & bakery',
  'Vlees & vis': 'Meat & fish',
  'Zuivel & eieren': 'Dairy & eggs',
  'Maaltijden & salades': 'Meals & salads',
  'Pasta, rijst & wereld': 'Pasta, rice & world',
  'Houdbaar': 'Cupboard',
  'Diepvries': 'Frozen',
  'Drinken': 'Drinks',
  'Huishouden': 'Household',
  'Kruiden & specerijen': 'Herbs & spices',

  // Delen
  'Deel je lijst': 'Share your list',
  'Wie de link opent, kijkt en vinkt mee op je lijst.': 'Whoever opens the link can view and check off your list.',
  'Je lijst wordt nog niet gedeeld.': 'Your list is not shared yet.',
  'Maak een deellink': 'Create a share link',
  'Deellink': 'Share link',
  'Deellink ophalen…': 'Fetching share link…',
  'Link kopiëren': 'Copy link',
  'Link gekopieerd': 'Link copied',
  'Kopiëren lukte niet. Houd de link ingedrukt en kies Kopiëren.': 'Copying failed. Press and hold the link and choose Copy.',
  'Deellink maken lukte niet. Probeer het opnieuw.': 'Creating the share link failed. Please try again.',
  'Je deellink ophalen lukte niet.': 'Could not fetch your share link.',
  'Nog niemand doet mee': 'Nobody has joined yet',
  '1 persoon doet mee': '1 person has joined',
  '{0} mensen doen mee': '{0} people have joined',
  'Stop met delen': 'Stop sharing',
  'Stoppen met delen?': 'Stop sharing?',
  'Wie de link heeft, ziet je lijst niet meer.': 'Anyone with the link will no longer see your list.',
  'Je lijst wordt niet meer gedeeld': 'Your list is no longer shared',
  'Stoppen met delen lukte niet. Probeer het opnieuw.': 'Stopping sharing failed. Please try again.',

  // Favorieten en altijd in huis
  'Vaak gekocht': 'Bought often',
  'Favorieten': 'Favourites',
  'Wat koop je vaak?': 'What do you buy often?',
  'Favoriet toevoegen': 'Add favourite',
  'Nog geen favorieten': 'No favourites yet',
  'Zet hier wat je elke week koopt. Eén tik en het staat op je lijst.': 'Put what you buy every week here. One tap and it is on your list.',
  'Zet op je lijst': 'Add to your list',
  'Zet {0} op je lijst': 'Add {0} to your list',
  '“{0}” op je lijst gezet': '“{0}” added to your list',
  '“{0}” verwijderd uit je favorieten': '“{0}” removed from your favourites',
  'Dit heb ik altijd in huis': 'I always have this at home',
  'Die staan uitgevinkt als je een recept op je lijst zet.': 'These are left unchecked when you put a recipe on your list.',
  'Wat heb je altijd in huis?': 'What do you always have at home?',
  'Bijvoorbeeld: sojasaus': 'For example: soy sauce',
  'Toevoegen aan altijd in huis': 'Add to always at home',
  'Haal {0} weg uit altijd in huis': 'Remove {0} from always at home',
  'Opslaan lukte niet. Probeer het opnieuw.': 'Saving failed. Please try again.',

  // Recepten
  'Wat kun je koken?': 'What can you cook?',
  'Recept toevoegen': 'Add recipe',
  'Recept': 'Recipe',
  '1 recept': '1 recipe',
  '{0} recepten': '{0} recipes',
  '{0} van je {1} recepten': '{0} of your {1} recipes',
  ' · {0} maak je het vaakst': ' · you make {0} most often',
  '{0} {1} gezien': '{0} {1} seen',
  'product': 'product',
  'producten': 'products',
  '{0} {1} met “{2}”': '{0} {1} with “{2}”',
  'recept': 'recipe',
  'recepten': 'recipes',
  'Zoek in je recepten': 'Search your recipes',
  'Zoek op naam of ingrediënt': 'Search by name or ingredient',
  'Zoekopdracht wissen': 'Clear search',
  'Nu nieuwste eerst, sorteer op naam': 'Newest first now; sort by name',
  'Nu op naam, sorteer op nieuwste': 'By name now; sort by newest',
  'Alles': 'All',
  'Alle': 'All',
  'Beheren': 'Manage',
  'Categorieën beheren': 'Manage categories',
  'Je hebt {0} {1} in huis.': 'You have {0} {1} at home.',
  'Niets gevonden voor “{0}”.': 'Nothing found for “{0}”.',
  'Nog geen recept in “{0}”. Open een recept en zet het label erbij.': 'No recipe in “{0}” yet. Open a recipe and add the label.',
  'Bonuschef kijkt elke woensdag mee': 'Bonuschef checks in every Wednesday',
  'Hoe meer recepten hier staan, hoe vaker er iets van jullie in de bonus ligt.': 'The more recipes you keep here, the more often one of yours is on offer.',
  'courgette · pesto · penne': 'courgette · pesto · penne',
  'kip · broccoli': 'chicken · broccoli',
  'zalm · citroen': 'salmon · lemon',
  'Zo gaat jouw kookboek eruitzien': 'This is what your cookbook will look like',
  'Plak een link van TikTok, Instagram, YouTube of een receptsite. Ook zonder foto krijgt elk recept een eigen gezicht.': 'Paste a link from TikTok, Instagram, YouTube or a recipe site. Even without a photo, every recipe gets a face of its own.',
  'Link plakken': 'Paste a link',
  'Zelf invullen': 'Type it yourself',
  'Vijf per maand gratis · zelf typen kan altijd': 'Five a month free · typing yourself is always free',
  'ingrediënt': 'ingredient',
  'ingrediënten': 'ingredients',
  '· voor {0}': '· serves {0}',
  '{0} openen': 'Open {0}',
  'Nieuw recept': 'New recipe',
  'Instagram laat ons deze post niet lezen. Plak hier de tekst van de post.': 'Instagram does not let us read this post. Paste the text of the post here.',
  'In deze link staat geen recept. Plak de tekst van de post, of vul het zelf in.': 'There is no recipe in this link. Paste the text of the post, or type it yourself.',
  'Plak een link of de tekst van een recept': 'Paste a link or the text of a recipe',
  'Plak link': 'Paste link',
  'Recept ophalen': 'Fetch recipe',
  'Bezig…': 'Working…',
  'Tegoed op': 'Allowance used up',
  'Je recepten van deze maand zijn op. Zelf invullen kan altijd.': 'Your recipes for this month are used up. Typing one yourself is always free.',
  'Nog {0} van {1} recepten deze maand. Zelf invullen kan altijd.': '{0} of {1} recipes left this month. Typing one yourself is always free.',
  'Liever zelf invullen': 'Rather type it yourself',
  '· Je kunt alles hieronder aanpassen.': '· You can change everything below.',
  'Recipe preview': 'Recipe preview',
  'Naam van het recept': 'Recipe name',
  'Korte beschrijving': 'Short description',
  'Link naar het recept (optioneel)': 'Link to the recipe (optional)',
  'Ingrediënten (één per regel)': 'Ingredients (one per line)',
  "Kipfilet (500g)\nRijst (300g)\nSojasaus": "Chicken breast (500g)\nRice (300g)\nSoy sauce",
  "Kipfilet (500g)\nRijst (300g)": "Chicken breast (500g)\nRice (300g)",
  'Kijk deze hoeveelheden even na': 'Double-check these amounts',
  'Kijk deze hoeveelheid even na': 'Double-check this amount',
  'Deze hoeveelheid is geschat uit de video. Kijk hem even na.': 'This amount was estimated from the video. Please double-check it.',
  'Aantal personen': 'Number of people',
  'Aantal': 'Quantity',
  'Categorieën': 'Categories',
  'Voorstel:': 'Suggestion:',
  'Instructies': 'Instructions',
  "1. Verwarm de oven voor op 180°C\n2. Kruid de kip...\n3. Bak 25 minuten...": "1. Preheat the oven to 180°C\n2. Season the chicken...\n3. Bake for 25 minutes...",
  '1. Verwarm de oven voor...': '1. Preheat the oven...',
  '← Terug': '← Back',
  'Vertaal naar NL': 'Translate to English',
  'Vertalen...': 'Translating...',
  'Voedingswaarden': 'Nutrition',
  'Recept opslaan': 'Save recipe',
  'Recept toegevoegd!': 'Recipe added!',
  'Recept opgehaald! Je kunt alles nog aanpassen.': 'Recipe fetched! You can still change everything.',
  'Alleen de titel gevonden, geen ingrediënten. Vul die zelf aan.': 'Only the title was found, no ingredients. Add those yourself.',
  'Recept ophalen lukte niet. Controleer je verbinding en probeer het opnieuw.': 'Fetching the recipe failed. Check your connection and try again.',
  'Controleer de link en probeer opnieuw.': 'Check the link and try again.',
  'Je klembord is leeg. Kopieer eerst de link of de tekst.': 'Your clipboard is empty. Copy the link or the text first.',
  'Plakken lukte niet. Houd het veld ingedrukt en kies Plakken.': 'Pasting failed. Press and hold the field and choose Paste.',
  'Vul eerst een recept in om te vertalen': 'Fill in a recipe first to translate it',
  'Recept vertaald naar Nederlands!': 'Recipe translated to English!',
  'Kon recept niet vertalen: {0}': 'Could not translate the recipe: {0}',
  'Voeg eerst ingrediënten toe': 'Add ingredients first',
  'Macronutriënten berekend!': 'Nutrition calculated!',
  'Kon macronutriënten niet berekenen: {0}': 'Could not calculate nutrition: {0}',
  'Van de website': 'From the website',
  'Uit de beschrijving': 'From the description',
  'Van de receptsite achter de link': 'From the recipe site behind the link',
  'Uit de video · hoeveelheden nakijken': 'From the video · check the amounts',
  'Geen recept gevonden': 'No recipe found',
  'Uit geplakte tekst': 'From pasted text',
  'Recept zoeken…': 'Looking for the recipe…',
  'Link lezen…': 'Reading the link…',
  'Nog even, we kijken de video…': 'One moment, we are watching the video…',
  'Nog even geduld…': 'Just a moment…',
  'Bewerken': 'Edit',
  'Recept bewerken': 'Edit recipe',
  'Naam recept': 'Recipe name',
  'Recept URL (optioneel)': 'Recipe URL (optional)',
  'Wijzigingen opslaan': 'Save changes',
  'Recept opgeslagen': 'Recipe saved',
  'Opslaan': 'Save',
  'Bekijken': 'View',
  'Origineel bekijken': 'View original',
  'Origineel recept bekijken': 'View original recipe',
  'Ingrediënten': 'Ingredients',
  'Bereiding': 'Method',
  'Voor {0} {1}': 'For {0} {1}',
  'Voor {0} personen': 'For {0} people',
  'Categorie': 'Category',
  'Op de lijst zetten': 'Put on the list',
  'Op de lijst': 'Add to list',
  'Dit recept heeft geen ingrediënten.': 'This recipe has no ingredients.',
  'Meer personen': 'More people',
  'Minder personen': 'Fewer people',
  'Aangepast van {0} naar {1}': 'Adjusted from {0} to {1}',
  'Heb je waarschijnlijk al': 'You probably already have',
  'item': 'item',
  'items': 'items',
  '{0} op je lijst gezet': '{0} added to your list',
  'Op je lijst zetten lukte niet. Probeer het opnieuw.': 'Adding to your list failed. Please try again.',
  'Bekijk lijst': 'View list',
  'Nog geen voedingswaarden': 'No nutrition yet',
  'Bereken ze op basis van de ingrediënten.': 'Calculate them from the ingredients.',
  'Voedingswaarden berekenen': 'Calculate nutrition',
  'Berekenen...': 'Calculating...',
  'Herberekenen...': 'Recalculating...',
  'Opnieuw berekenen': 'Recalculate',
  'Voedingswaarden berekend': 'Nutrition calculated',
  'Voedingswaarden berekenen lukte niet. Probeer het opnieuw.': 'Calculating nutrition failed. Please try again.',
  'Voedingswaarden — {0}': 'Nutrition — {0}',
  'Geschatte waarden per totaal recept': 'Estimated values for the whole recipe',
  'Eiwit': 'Protein',
  'Koolhydraten': 'Carbs',
  'Vet': 'Fat',
  'Vezels': 'Fibre',
  'Even kijken wat er met je lijst te koken valt…': 'Seeing what you can cook with your list…',
  'Zet eerst wat op je lijst; daarna bedenken we er gerechten bij.': 'Put something on your list first; then we come up with dishes for it.',
  'Voeg minstens 2 ingrediënten toe aan je boodschappenlijst': 'Add at least 2 ingredients to your grocery list',
  'Geen suggesties gevonden': 'No suggestions found',
  'Kon geen suggesties ophalen: {0}': 'Could not fetch suggestions: {0}',
  '"{0}" toegevoegd aan je recepten!': '"{0}" added to your recipes!',
  'Extra nodig:': 'Also needed:',
  'Bedenk iets anders': 'Think of something else',
  'Even geduld…': 'One moment…',

  // Categorieën
  'Eigen categorie': 'Own category',
  'Bijvoorbeeld: Vega': 'For example: Veggie',
  'Maken': 'Create',
  'Ook handig:': 'Also handy:',
  'Je categorieën': 'Your categories',
  'Waar hoort dit bij?': 'Where does this belong?',
  'Naam wijzigen, andere kleur kiezen of weggooien.': 'Rename, pick another colour, or delete.',
  'Terug naar dit recept': 'Back to this recipe',
  'Je hebt nog geen categorieën gemaakt.': 'You have not made any categories yet.',
  'Je hebt “{0}” al': 'You already have “{0}”',
  '“{0}” heet nu “{1}”': '“{0}” is now called “{1}”',
  '“{0}” verwijderd': '“{0}” removed',
  '“{0}” verwijderen?': 'Delete “{0}”?',
  'Het label verdwijnt van {0}. De recepten zelf blijven staan.': 'The label is removed from {0}. The recipes themselves stay.',
  'Deze categorie wordt nergens gebruikt.': 'This category is not used anywhere.',
  'Kleur {0}': 'Colour {0}',
  'Naam wijzigen': 'Rename',
  '{0} verwijderen': 'Delete {0}',

  // Bonus
  'Deze week': 'This week',
  'De bonus van deze week wordt opgehaald': 'Fetching this week’s offers',
  '1 van je {0} recepten is goedkoper': '1 of your {0} recipes is cheaper',
  '{0} van je {1} recepten zijn goedkoper': '{0} of your {1} recipes are cheaper',
  '{0} aanbiedingen bekeken': '{0} offers checked',
  'Albert Heijn, elke woensdag nieuw': 'Albert Heijn, new every Wednesday',
  't/m {0}': 'until {0}',
  '{0}, nog {1}': '{0}, {1} left',
  '1 dag': '1 day',
  '{0} dagen': '{0} days',
  'Bonus van deze week ophalen': 'Fetching this week’s offers',
  '{0} aanbiedingen langs je recepten': '{0} offers against your recipes',
  'Alle aanbiedingen langs je recepten': 'All offers against your recipes',
  'Alle aanbiedingen van deze week': 'All offers this week',
  'Je hoeft niet te wachten — het staat er zo.': 'No need to wait — it will be here in a moment.',
  'nog ± {0} sec': 'about {0} sec left',
  'Vorige keer scheelde het jullie {0}.': 'Last time it saved you {0}.',
  'De bonus ophalen lukte niet.': 'Could not fetch the offers.',
  'aanbiedingen keken we langs': 'offers we looked through',
  'We weten nog niet wat jij kookt': 'We do not know yet what you cook',
  'Bewaar een recept, dan kijkt CoupleCart elke week welke ervan goedkoper zijn.': 'Save a recipe and CoupleCart checks every week which ones are cheaper.',
  'Eerste recept ophalen': 'Fetch your first recipe',
  'Deze week niets van jou': 'Nothing of yours this week',
  'Geen van je {0} recepten zit er deze week in. De aanbiedingen wisselen woensdag.': 'None of your {0} recipes is on offer this week. The offers change on Wednesday.',
  'Laat iets verzinnen uit de bonus': 'Have something made up from the offers',
  'Even koken…': 'Cooking…',
  '{0} van {1} in de bonus': '{0} of {1} on offer',
  'goedkoper deze week': 'cheaper this week',
  'Drie avonden uit de bonus': 'Three evenings from the offers',
  'Gemaakt met wat deze week in de aanbieding ligt.': 'Made with what is on offer this week.',
  'Drie andere verzinnen': 'Make up three others',
  'Laat iets verzinnen': 'Make something up',
  '{0} min ·': '{0} min ·',
  '· ± {0} goedkoper': '· about {0} cheaper',
  'Bewaard': 'Saved',
  'Bewaren': 'Save',
  '{0} boodschappen op je lijst': '{0} items on your list',
  'Ingrediënten en bereiding': 'Ingredients and method',
  'Recepten bedenken lukte niet. Probeer het zo nog eens.': 'Making up recipes failed. Try again in a moment.',
  '“{0}” staat bij je recepten': '“{0}” is in your recipes',
  'Wel in de bonus deze week': 'On offer this week',
  'Nog {0} aanbiedingen': '{0} more offers',
  'Minder tonen': 'Show fewer',
  'Prijzen en acties komen van Albert Heijn.': 'Prices and offers come from Albert Heijn.',

  // Voorraad
  '{0} producten': '{0} products',
  '· {0} bijna op': '· {0} running low',
  'Zoek in je kast': 'Search your pantry',
  'Zoeken in je kast': 'Search your pantry',
  'Zoeken sluiten': 'Close search',
  'Kast scannen': 'Scan pantry',
  'Bijna op': 'Running low',
  'bijna op': 'running low',
  'op': 'out',
  'Bijna op · {0}': 'Running low · {0}',
  'Zelf iets toevoegen': 'Add something yourself',
  'Toevoegen aan de kast': 'Add to pantry',
  'Kastfoto’s zijn op, op {0} staat je tegoed weer op {1}.': 'Pantry photos are used up; on {0} your allowance is back to {1}.',
  'Nog {0} van {1} kastfoto’s deze maand': '{0} of {1} pantry photos left this month',
  'Niets gevonden.': 'Nothing found.',
  'foto · plank in beeld': 'photo · shelf in view',
  'Maak een foto van je plank': 'Take a photo of your shelf',
  'CoupleCart leest welke producten erop staan. Je ziet eerst wat er herkend is en vinkt zelf af wat klopt.': 'CoupleCart reads which products are on it. You first see what was recognised and tick what is right.',
  'Foto maken': 'Take a photo',
  'Zelf typen': 'Type it yourself',
  'Vijf foto’s per maand gratis': 'Five photos a month free',
  'Vink je iets af op je lijst? Dan zet CoupleCart het hier vanzelf bij.': 'Check something off on your list? CoupleCart adds it here by itself.',
  'Foto lezen…': 'Reading the photo…',
  'De foto lezen lukte niet. Probeer het nog eens.': 'Reading the photo failed. Please try again.',
  'Je foto’s zijn op': 'Your photos are used up',
  '“{0}” staat er al in, er is er eentje bij gezet': '“{0}” was already in there; one more was added',
  '“{0}” staat al in je kast': '“{0}” is already in your pantry',
  '“{0}” uit je kast gehaald': '“{0}” removed from your pantry',
  'Zet hem in de bijna-op-rij': 'Put it in the running-low row',
  'Vink af wat klopt. Twijfelgevallen staan onderaan.': 'Tick what is right. Doubtful ones are at the bottom.',
  'Niets herkend': 'Nothing recognised',
  'Probeer het nog eens van dichterbij, met de etiketten naar voren.': 'Try again from closer by, with the labels facing forward.',
  'staat al in je kast': 'already in your pantry',
  'label niet goed leesbaar': 'label not clearly readable',
  'Naam van {0}': 'Name of {0}',
  '{0} aanpassen': 'Edit {0}',
  'Iets gemist? Typ het erbij': 'Missed something? Type it in',
  'Opnieuw': 'Again',
  '{0} toevoegen': 'Add {0}',
  'Canvas niet beschikbaar': 'Canvas not available',
  'Foto lezen lukte niet': 'Reading the photo failed',

  // Tegoed en Plus
  'recepten ophalen': 'recipe fetches',
  'kastfoto’s': 'pantry photos',
  'kastfoto’s deze maand': 'pantry photos this month',
  'Je hebt Plus: alles onbeperkt, voor jullie samen.': 'You have Plus: everything unlimited, for the two of you.',
  'Elke maand vijf van allebei. Op {0} staat de teller weer op nul.': 'Five of each every month. On {0} the counter resets.',
  'onbeperkt': 'unlimited',
  '{0} van {1}': '{0} of {1}',
  'Je Plus is met de hand gegeven': 'Your Plus was granted by hand',
  'Er staat geen abonnement bij Stripe om te beheren.': 'There is no subscription at Stripe to manage.',
  'Het klantportaal openen lukte niet.': 'Opening the customer portal failed.',
  'Beheer je abonnement': 'Manage your subscription',
  'Onbeperkt recepten ophalen en scannen, voor het hele huishouden. Binnenkort te koop.': 'Unlimited recipe fetches and scans, for the whole household. Available soon.',
  'Je {0} {1} van deze maand zijn op': 'Your {0} {1} for this month are used up',
  'Op {0} staat je tegoed weer op {1}. Je lijst, je recepten en je voorraad blijven gewoon werken.': 'On {0} your allowance is back to {1}. Your list, recipes and pantry keep working as usual.',
  'CoupleCart Plus': 'CoupleCart Plus',
  'Onbeperkt recepten ophalen uit een link of video': 'Unlimited recipes from a link or video',
  'Onbeperkt je kast scannen met een foto': 'Unlimited pantry scans from a photo',
  'Bonuschef, receptsuggesties en voedingswaarden': 'Bonuschef, recipe suggestions and nutrition',
  'Eén keer voor jullie samen, ook voor je partner': 'One plan for the two of you, your partner included',
  'Per maand': 'Per month',
  'Per jaar': 'Per year',
  'maandelijks opzegbaar': 'cancel monthly',
  '4 maanden gratis': '4 months free',
  'Opzeggen wanneer je wil, bij Stripe zelf': 'Cancel whenever you like, at Stripe itself',
  'Nu even niet': 'Not now',
  'Plus is er bijna': 'Plus is almost here',
  'Betalen staat nog niet aan': 'Payments are not switched on yet',
  'Betalen staat nog niet aan. Mail couplecart@gmail.com als je het eerder wil.': 'Payments are not switched on yet. Email couplecart@gmail.com if you want it sooner.',
  'Afrekenen lukte niet. Probeer het zo nog eens.': 'Checkout failed. Try again in a moment.',
  'Geen betaalpagina gekregen': 'No payment page received',
  'Geen klantportaal gekregen': 'No customer portal received',
  'Je gratis tegoed voor deze maand is op': 'Your free allowance for this month is used up',

  // Weekplan
  'Maaltijd': 'Meal',
  '“{0}” uit je weekplan gehaald': '“{0}” removed from your week plan',

  // Inloggen
  'Two People. One Cart.': 'Two People. One Cart.',
  'Doorgaan met Google': 'Continue with Google',
  'of met e-mail': 'or with email',
  'E-mailadres': 'Email address',
  'Wachtwoord': 'Password',
  'Toon wachtwoord': 'Show password',
  'Verberg wachtwoord': 'Hide password',
  'Inloggen': 'Sign in',
  'Account aanmaken': 'Create account',
  'Al een account?': 'Already have an account?',
  'Nog geen account?': 'No account yet?',
  'Doorgaan zonder account': 'Continue without an account',
  'De verificatiemail kan in je spamfolder belanden.': 'The verification email may end up in your spam folder.',
  'Verificatie e-mail verstuurd! Check je inbox en spamfolder.': 'Verification email sent! Check your inbox and spam folder.',
  'Google login mislukt': 'Google sign-in failed',
  'Er ging iets mis': 'Something went wrong',
  'Er ging iets mis bij het starten als gast': 'Something went wrong starting as a guest',
  'Voorwaarden': 'Terms',
  'Privacy': 'Privacy',
  'Cookies': 'Cookies',
};
